logLevel: "info"
interval: "30s"
scrapeTimeout: "1s"
serviceMonitorNamingPattern: "sm-%"
selector:
  matchLabels:
    app.kubernetes.io/instance: blackbox-exporter
exclude:
  matchLabels:
    blackbox-operator-scrape: "false"
defaultModule: http_2xx
protocolModuleMappings:
  TCP: tcp_connect