apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  labels:
    managed-by: istio-operator
  name: external-service
  namespace: istio-system
spec:
  hosts:
    - www.ebay.de
    - example.com
    - foo.com
  ports:
    - name: https
      number: 443
      protocol: HTTPS
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-service-tcp
  namespace: istio-system
spec:
  hosts:
    - google.de
  location: MESH_EXTERNAL
  ports:
    - name: tcp
      number: 443
      protocol: TCP
  resolution: DNS